/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ece651.sp22.yy340.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;

public class App {
  final Board<Character> theBoard;
  final BoardTextView view;
  final BufferedReader inputReader;
  final PrintStream out;

  public App(Board<Character> theBoard, Reader inputSource, PrintStream out) {
    this.theBoard = theBoard;
    this.view = new BoardTextView(theBoard);
    this.inputReader = new BufferedReader(inputSource);
    this.out = out;
  }

  public Placement readPlacement(String prompt) throws IOException {
    out.println(prompt);
    String s = inputReader.readLine();
    return new Placement(s);
  }

  public void doOnePlacement() throws IOException {
    Placement pos = readPlacement("Where would you like to put your ship?");
    RectangleShip<Character> s = new RectangleShip<Character>(pos.getWhere(), 's', '*');
    theBoard.tryAddShip(s);
    out.print(view.displayMyOwnBoard());
  }

  public static void main(String[] args) throws IOException {
    System.out.println("What to do next?\n");
    Board<Character> myBoard = new BattleShipBoard<Character>(10, 20);
    App app = new App(myBoard, new InputStreamReader(System.in), System.out);
    app.doOnePlacement();
  }

}
