/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ece651.sp22.yy340.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;

public class App {

  TextPlayer player1;
  TextPlayer player2;

  public App(TextPlayer player1, TextPlayer player2) {
    this.player1 = player1;
    this.player2 = player2;
  }

  public void doPlacementPhase() throws IOException {
    player1.doPlacementPhase();
    player2.doPlacementPhase();
  }

  public void doAttackingPhase() throws IOException {
    while (true) {
      //Player 1
      player1.playOneTurn(player2.theBoard, player2.view);
      if (player2.theBoard.CheckingLost()) {
        player1.textPlayer_print(player2.name);
        return;
      }
      //Player 2
      player2.playOneTurn(player1.theBoard, player1.view);
      if (player1.theBoard.CheckingLost()) {
        player2.textPlayer_print(player1.name);
        return;
      }

    }
  }

  public static void main(String[] args) throws IOException {
    BufferedReader buffer_reader = new BufferedReader(new InputStreamReader(System.in));
    //V1ShipFactory v1shipfactory = new V1ShipFactory();
    V2ShipFactory v2shipfactory = new V2ShipFactory();
    Board<Character> b1 = new BattleShipBoard<Character>(10, 20, 'X');
    Board<Character> b2 = new BattleShipBoard<Character>(10, 20, 'X');
    TextPlayer player1 = new TextPlayer("A", b1, buffer_reader, System.out, v2shipfactory);
    TextPlayer player2 = new TextPlayer("B", b2, buffer_reader, System.out, v2shipfactory);
    App app = new App(player1, player2);
    app.doPlacementPhase();
    app.doAttackingPhase();
    return;
  }

}
